# Generated by Django 4.2.14 on 2024-07-26 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Expenses', '0003_split_payer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='split',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Expenses.expenses'),
        ),
        migrations.AlterField(
            model_name='split',
            name='payer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
