# Generated by Django 4.2.14 on 2024-07-26 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Expenses', '0004_alter_split_expense_alter_split_payer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='split',
            name='group',
        ),
    ]
