# Generated by Django 4.2.13 on 2024-07-30 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Expenses', '0005_remove_split_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='split',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses_split', to='Expenses.expenses'),
        ),
    ]
