# Generated by Django 4.2.13 on 2024-07-30 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Expenses', '0006_alter_split_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='split',
            name='payer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses_payer', to=settings.AUTH_USER_MODEL),
        ),
    ]
