# Generated by Django 4.2.14 on 2024-07-26 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Friends', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequests',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='friendrequests',
            name='timestamp',
        ),
    ]
