# Generated by Django 4.2.14 on 2024-07-23 11:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentications', '0003_alter_user_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friendsfield', to=settings.AUTH_USER_MODEL),
        ),
    ]
